// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'candidate': string;
  'candidateMeta': string;
  'candidateSelected': string;
  'candidateTitle': string;
  'card': string;
  'cardBody': string;
  'cardTitle': string;
  'checkbox': string;
  'detailHeader': string;
  'detailTitle': string;
  'error': string;
  'field': string;
  'fieldLabel': string;
  'form': string;
  'grid': string;
  'input': string;
  'intro': string;
  'list': string;
  'muted': string;
  'poster': string;
  'posterPlaceholder': string;
  'primaryButton': string;
  'releaseCard': string;
  'releaseList': string;
  'releaseReason': string;
  'releaseTitle': string;
  'releaseTop': string;
  'reviewPanel': string;
  'searchForm': string;
  'section': string;
  'select': string;
  'selectedNotice': string;
  'statusEligible': string;
  'statusRejected': string;
  'statusReview': string;
  'toolbar': string;
}
export const cssExports: CssExports;
export default cssExports;
